### ISSUE TITLE
Where is the artwork?

### ISSUE THREAD

**Issue by ItsMariusX** [MindfulOutlet/Sposify#1]
Where is the artwork on liked songs?
![553F94A3-522B-42A2-823B-093157461F79](https://user-images.githubusercontent.com/52087085/76637412-62a6a200-6553-11ea-965e-d086d99a6758.png)

**Comment by MindfulOutlet** [comment]
it should be there what is your Spotify Version and if you uninstall Sposify does it show the artwork?

**Comment by ItsMariusX** [comment]
I’m on latest version and i just re installed spotify and same thing .

![ADBC7A5D-BA29-4278-9728-ECAEF30DE0D1](https://user-images.githubusercontent.com/52087085/76641448-4ce8ab00-655a-11ea-92a2-8b12f7c1a820.png)

**Comment by MindfulOutlet** [comment]
hmm if you uninstall my Sposify tweak does it show the album artwork?

**Comment by ItsMariusX** [comment]
still cannot see album artwork on liked songs   even after i removed sposify

**Comment by ItsMariusX** [comment]
but on other playlists works fine ..

![6D801E8A-3AD2-4A09-8373-3875BB2EC4B3](https://user-images.githubusercontent.com/52087085/76642489-f67c6c00-655b-11ea-9b78-b9e1229514c7.png)

**Comment by MindfulOutlet** [comment]
maybe it's groovify causing the issue?

**Comment by ItsMariusX** [comment]
Yop , just disabled groovify and all good now .
Thank you 🙏
